### ISSUE TITLE
Create Embedded Jetty Instance & Servlet

### ISSUE THREAD

**Issue by samanthamccabe** [samanthamccabe/toolbox-gui#1]
http://www.hascode.com/2013/07/embedding-jetty-or-tomcat-in-your-java-application/

**Comment by HallowXIII** [comment]
I still don't think this is a good idea. "Usable from the browser" sounds good, but becomes a burden if you have to open an external application and then navigate to a local service from your browser -- this is a) one step too many for and b) unfamiliar to most users. So that becomes a moot point.

Second, as a default method of providing a GUI, this is quite inefficient because you need to have a whole web browser running to display it, plus the small but existing overhead of running an essentially extraneous HTTP servlet even if the browser is considered incidental (because most people will have one open anyway).

JavaFX would very likely be the better alternative (it also provides an in-app web view in case you're dead set on producing browser-readable output. Yay user choice!).

**Comment by samanthamccabe** [comment]
That may meet our needs better. I'd certainly feel better about the whole thing. There are some data views that would be best done using D3, at least out of anything I've seen.

I've been told JavaFX is a good framework, so I'm definitely willing to give that a try. Also, there may be entirely reasonable ways of doing data visualization that I'm not yet familiar with.
